export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_VIEW';
export const REQUEST_ARTICLE_VIEW = 'REQUEST_ARTICLE_VIEW';
export const FETCH_ARTICLE_VIEW = 'FETCH_ARTICLE_VIEW';
export const RECEIVE_ARTICLE_VIEW = 'RECEIVE_ARTICLE_VIEW';
export const REQUEST_TYPE_LIST = 'REQUEST_TYPE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const FETCH_LOGIN = 'FETCH_LOGIN';
export const RECEUVE_LOGIN = 'RECEUVE_LOGIN';

export const RECEUVE_REGISTER = 'RECEUVE_REGISTER';
export const FETCH_REGISTER = 'FETCH_REGISTER';
export const REQUEST_REGISTER = 'REQUEST_REGISTER';

export const REQUEST_SENDEMAIL = 'REQUEST_SENDEMAIL';
export const FETCH_SENDEMAIL = 'FETCH_SENDEMAIL';
export const RECEUVE_SENDEMAIL = 'RECEUVE_SENDEMAIL';

export const REQUEST_FORGETPASSWORD = 'REQUEST_FORGETPASSWORD';
export const FETCH_FORGETPASSWORD = 'FETCH_FORGETPASSWORD';
export const RECEUVE_FORGETPASSWORD = 'RECEUVE_FORGETPASSWORD';

export const REQUEST_CHAT = 'REQUEST_CHAT';
export const FETCH_CHAT = 'FETCH_CHAT';
export const RECEIVE_CHAT = 'RECEIVE_CHAT';

export const REQUEST_FRIENDS = 'REQUEST_FRIENDS';
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS';

export const REQUEST_QUERY_USER = 'REQUEST_QUERY_USER';
export const FETCH_QUERY_USER = 'FETCH_QUERY_USER';
export const RECEIVE_QUERY_USER = 'RECEIVE_QUERY_USER';


export const REQUEST_NEW_FRIEND = 'REQUEST_NEW_FRIEND';
export const FETCH_NEW_FRIEND = 'FETCH_NEW_FRIEND';
export const RECEIVE_NEW_FRIEND = 'RECEIVE_NEW_FRIEND';