export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_VIEW';
export const REQUEST_ARTICLE_VIEW = 'REQUEST_ARTICLE_VIEW';
export const FETCH_ARTICLE_VIEW = 'FETCH_ARTICLE_VIEW';
export const RECEIVE_ARTICLE_VIEW = 'RECEIVE_ARTICLE_VIEW';
export const REQUEST_TYPE_LIST = 'REQUEST_TYPE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const FETCH_LOGIN = 'FETCH_LOGIN';
export const RECEUVE_LOGIN = 'RECEUVE_LOGIN';

export const RECEUVE_REGISTER = 'RECEUVE_REGISTER';
export const FETCH_REGISTER = 'FETCH_REGISTER';
export const REQUEST_REGISTER = 'REQUEST_REGISTER';

export const REQUEST_SENDEMAIL = 'REQUEST_SENDEMAIL';
export const FETCH_SENDEMAIL = 'FETCH_SENDEMAIL';
export const RECEUVE_SENDEMAIL = 'RECEUVE_SENDEMAIL';

export const REQUEST_FORGETPASSWORD = 'REQUEST_FORGETPASSWORD';
export const FETCH_FORGETPASSWORD = 'FETCH_FORGETPASSWORD';
export const RECEUVE_FORGETPASSWORD = 'RECEUVE_FORGETPASSWORD';

export const REQUSET_USERLIST = 'REQUSET_USERLIST';
export const RECEUVE_USERLIST = 'RECEUVE_USERLIST';

export const REQUSET_CONTACT_LIST = 'REQUSET_CONTACT_LIST';
export const FETCH_CONTACT_LIST = 'FETCH_CONTACT_LIST';
export const RECEIVE_CONTACT_LIST = 'RECEIVE_CONTACT_LIST';

export const REQUEST_FIND = 'REQUEST_FIND';
export const FETCH_FIND = 'FETCH_FIND';
export const RECEUVE_FIND = 'RECEUVE_FIND';



